<?php
/**
 * MarketPlaceStatusApiResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EzzeSiftuz\ProductsV2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public Partner Product API
 *
 * Manage your product data, send images and                   much more.
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EzzeSiftuz\ProductsV2;

/**
 * MarketPlaceStatusApiResultTest Class Doc Comment
 *
 * @category    Class
 * @description MarketPlaceStatusApiResult
 * @package     EzzeSiftuz\ProductsV2
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MarketPlaceStatusApiResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MarketPlaceStatusApiResult"
     */
    public function testMarketPlaceStatusApiResult()
    {
    }

    /**
     * Test attribute "market_place_status"
     */
    public function testPropertyMarketPlaceStatus()
    {
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
    }
}
